#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("seq1_address0", 7, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("seq1_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("seq1_q0", 8, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("seq2_address0", 7, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("seq2_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("seq2_q0", 8, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("aligned_seq1_address0", 7, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("aligned_seq1_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("aligned_seq1_we0", 1, hls_out, 2, "ap_memory", "mem_we", 1),
	Port_Property("aligned_seq1_d0", 8, hls_out, 2, "ap_memory", "mem_din", 1),
	Port_Property("aligned_seq1_q0", 8, hls_in, 2, "ap_memory", "mem_dout", 1),
	Port_Property("n", 32, hls_out, 3, "ap_vld", "out_data", 1),
	Port_Property("n_ap_vld", 1, hls_out, 3, "ap_vld", "out_vld", 1),
	Port_Property("aligned_seq2_address0", 7, hls_out, 4, "ap_memory", "mem_address", 1),
	Port_Property("aligned_seq2_ce0", 1, hls_out, 4, "ap_memory", "mem_ce", 1),
	Port_Property("aligned_seq2_we0", 1, hls_out, 4, "ap_memory", "mem_we", 1),
	Port_Property("aligned_seq2_d0", 8, hls_out, 4, "ap_memory", "mem_din", 1),
	Port_Property("aligned_seq2_q0", 8, hls_in, 4, "ap_memory", "mem_dout", 1),
	Port_Property("m", 32, hls_out, 5, "ap_vld", "out_data", 1),
	Port_Property("m_ap_vld", 1, hls_out, 5, "ap_vld", "out_vld", 1),
	Port_Property("l", 32, hls_out, 6, "ap_vld", "out_data", 1),
	Port_Property("l_ap_vld", 1, hls_out, 6, "ap_vld", "out_vld", 1),
};
const char* HLS_Design_Meta::dut_name = "SmithWaterman";
