// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "traceback.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic traceback::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic traceback::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<11> traceback::ap_ST_fsm_state1 = "1";
const sc_lv<11> traceback::ap_ST_fsm_state2 = "10";
const sc_lv<11> traceback::ap_ST_fsm_state3 = "100";
const sc_lv<11> traceback::ap_ST_fsm_state4 = "1000";
const sc_lv<11> traceback::ap_ST_fsm_state5 = "10000";
const sc_lv<11> traceback::ap_ST_fsm_state6 = "100000";
const sc_lv<11> traceback::ap_ST_fsm_state7 = "1000000";
const sc_lv<11> traceback::ap_ST_fsm_state8 = "10000000";
const sc_lv<11> traceback::ap_ST_fsm_state9 = "100000000";
const sc_lv<11> traceback::ap_ST_fsm_state10 = "1000000000";
const sc_lv<11> traceback::ap_ST_fsm_state11 = "10000000000";
const sc_lv<32> traceback::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> traceback::ap_const_lv32_1 = "1";
const sc_lv<1> traceback::ap_const_lv1_1 = "1";
const sc_lv<32> traceback::ap_const_lv32_2 = "10";
const sc_lv<1> traceback::ap_const_lv1_0 = "0";
const sc_lv<32> traceback::ap_const_lv32_3 = "11";
const sc_lv<32> traceback::ap_const_lv32_5 = "101";
const sc_lv<32> traceback::ap_const_lv32_8 = "1000";
const sc_lv<32> traceback::ap_const_lv32_4 = "100";
const sc_lv<32> traceback::ap_const_lv32_7 = "111";
const sc_lv<32> traceback::ap_const_lv32_A = "1010";
const sc_lv<8> traceback::ap_const_lv8_0 = "00000000";
const sc_lv<8> traceback::ap_const_lv8_2D = "101101";
const sc_lv<32> traceback::ap_const_lv32_6 = "110";
const sc_lv<32> traceback::ap_const_lv32_9 = "1001";
const sc_lv<32> traceback::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_lv<32> traceback::ap_const_lv32_FFFFFFFD = "11111111111111111111111111111101";
const sc_lv<32> traceback::ap_const_lv32_FFFFFFFE = "11111111111111111111111111111110";
const sc_lv<15> traceback::ap_const_lv15_65 = "1100101";
const bool traceback::ap_const_boolean_1 = true;

traceback::traceback(sc_module_name name) : sc_module(name), mVcdFile(0) {
    SmithWaterman_mulbkb_U6 = new SmithWaterman_mulbkb<1,1,8,15,15>("SmithWaterman_mulbkb_U6");
    SmithWaterman_mulbkb_U6->din0(mul_ln130_fu_598_p0);
    SmithWaterman_mulbkb_U6->din1(mul_ln130_fu_598_p1);
    SmithWaterman_mulbkb_U6->dout(mul_ln130_fu_598_p2);
    SmithWaterman_mulbkb_U7 = new SmithWaterman_mulbkb<1,1,8,15,15>("SmithWaterman_mulbkb_U7");
    SmithWaterman_mulbkb_U7->din0(mul_ln133_fu_605_p0);
    SmithWaterman_mulbkb_U7->din1(mul_ln133_fu_605_p1);
    SmithWaterman_mulbkb_U7->dout(mul_ln133_fu_605_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_H_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( sext_ln130_fu_380_p1 );
    sensitive << ( sext_ln133_fu_429_p1 );
    sensitive << ( sext_ln140_fu_444_p1 );

    SC_METHOD(thread_H_address1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( sext_ln141_fu_448_p1 );

    SC_METHOD(thread_H_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_H_ce1);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_add_ln130_fu_375_p2);
    sensitive << ( trunc_ln130_fu_367_p1 );
    sensitive << ( mul_ln130_fu_598_p2 );

    SC_METHOD(thread_add_ln133_2_fu_424_p2);
    sensitive << ( trunc_ln140_fu_401_p1 );
    sensitive << ( mul_ln133_fu_605_p2 );

    SC_METHOD(thread_add_ln140_fu_405_p2);
    sensitive << ( mul_ln130_reg_651 );
    sensitive << ( trunc_ln140_fu_401_p1 );

    SC_METHOD(thread_add_ln141_fu_434_p2);
    sensitive << ( trunc_ln130_reg_646 );
    sensitive << ( mul_ln133_fu_605_p2 );

    SC_METHOD(thread_add_ln146_fu_361_p2);
    sensitive << ( len_assign_reg_259 );

    SC_METHOD(thread_aligned_seq1_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( and_ln142_reg_726 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( aligned_seq1_addr_4_reg_749 );
    sensitive << ( aligned_seq1_addr_5_reg_754 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( sext_ln165_fu_438_p1 );
    sensitive << ( sext_ln155_fu_523_p1 );
    sensitive << ( and_ln148_fu_506_p2 );
    sensitive << ( and_ln153_fu_517_p2 );
    sensitive << ( sext_ln150_fu_530_p1 );
    sensitive << ( sext_ln145_fu_536_p1 );
    sensitive << ( sext_ln69_fu_565_p1 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_aligned_seq1_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( and_ln142_reg_726 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( and_ln148_fu_506_p2 );
    sensitive << ( and_ln153_fu_517_p2 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_aligned_seq1_d0);
    sensitive << ( aligned_seq1_q0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( seq1_load_reg_716 );
    sensitive << ( and_ln142_reg_726 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( and_ln148_fu_506_p2 );
    sensitive << ( and_ln153_fu_517_p2 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_aligned_seq1_we0);
    sensitive << ( and_ln127_reg_637 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln130_fu_385_p2 );
    sensitive << ( and_ln142_reg_726 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( and_ln148_fu_506_p2 );
    sensitive << ( and_ln153_fu_517_p2 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_aligned_seq2_addr_3_gep_fu_186_p3);
    sensitive << ( and_ln142_reg_726 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( sext_ln155_fu_523_p1 );
    sensitive << ( and_ln148_fu_506_p2 );
    sensitive << ( and_ln153_fu_517_p2 );

    SC_METHOD(thread_aligned_seq2_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( and_ln142_reg_726 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( aligned_seq2_addr_5_reg_772 );
    sensitive << ( aligned_seq2_addr_6_reg_777 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( sext_ln165_fu_438_p1 );
    sensitive << ( sext_ln155_fu_523_p1 );
    sensitive << ( and_ln148_fu_506_p2 );
    sensitive << ( and_ln153_fu_517_p2 );
    sensitive << ( aligned_seq2_addr_3_gep_fu_186_p3 );
    sensitive << ( sext_ln150_fu_530_p1 );
    sensitive << ( sext_ln145_fu_536_p1 );
    sensitive << ( sext_ln69_1_fu_593_p1 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_aligned_seq2_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( and_ln142_reg_726 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( and_ln148_fu_506_p2 );
    sensitive << ( and_ln153_fu_517_p2 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_aligned_seq2_d0);
    sensitive << ( aligned_seq2_q0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( seq2_load_reg_721 );
    sensitive << ( and_ln142_reg_726 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( and_ln148_fu_506_p2 );
    sensitive << ( and_ln153_fu_517_p2 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_aligned_seq2_we0);
    sensitive << ( and_ln127_reg_637 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln130_fu_385_p2 );
    sensitive << ( and_ln142_reg_726 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( and_ln148_fu_506_p2 );
    sensitive << ( and_ln153_fu_517_p2 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_and_ln127_fu_355_p2);
    sensitive << ( icmp_ln127_fu_343_p2 );
    sensitive << ( icmp_ln127_1_fu_349_p2 );

    SC_METHOD(thread_and_ln142_fu_477_p2);
    sensitive << ( grp_fu_313_p2 );
    sensitive << ( icmp_ln142_1_fu_472_p2 );

    SC_METHOD(thread_and_ln148_fu_506_p2);
    sensitive << ( icmp_ln148_fu_495_p2 );
    sensitive << ( icmp_ln148_1_fu_501_p2 );

    SC_METHOD(thread_and_ln153_fu_517_p2);
    sensitive << ( grp_fu_313_p2 );
    sensitive << ( icmp_ln153_1_fu_512_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln66_1_fu_576_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln66_1_fu_576_p2 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln66_1_fu_576_p2 );
    sensitive << ( len_assign_reg_259 );

    SC_METHOD(thread_diag_score_1_fu_466_p2);
    sensitive << ( H_q0 );
    sensitive << ( select_ln134_fu_458_p3 );

    SC_METHOD(thread_grp_fu_313_p2);
    sensitive << ( H_q0 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( and_ln142_reg_726 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( and_ln148_fu_506_p2 );

    SC_METHOD(thread_i_1_fu_554_p2);
    sensitive << ( i_0_i_reg_271 );

    SC_METHOD(thread_i_2_fu_582_p2);
    sensitive << ( i_0_i2_reg_292 );

    SC_METHOD(thread_i_fu_410_p2);
    sensitive << ( i_0_load_reg_632 );

    SC_METHOD(thread_icmp_ln127_1_fu_349_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( j_0_fu_54 );

    SC_METHOD(thread_icmp_ln127_fu_343_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_fu_58 );

    SC_METHOD(thread_icmp_ln130_fu_385_p2);
    sensitive << ( H_q0 );
    sensitive << ( and_ln127_reg_637 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_icmp_ln134_fu_452_p2);
    sensitive << ( seq1_q0 );
    sensitive << ( seq2_q0 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_icmp_ln142_1_fu_472_p2);
    sensitive << ( H_load_reg_661 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( diag_score_1_fu_466_p2 );

    SC_METHOD(thread_icmp_ln148_1_fu_501_p2);
    sensitive << ( H_load_reg_661 );
    sensitive << ( and_ln142_reg_726 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( up_score_fu_489_p2 );

    SC_METHOD(thread_icmp_ln148_fu_495_p2);
    sensitive << ( H_q1 );
    sensitive << ( and_ln142_reg_726 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_icmp_ln153_1_fu_512_p2);
    sensitive << ( H_load_reg_661 );
    sensitive << ( and_ln142_reg_726 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( and_ln148_fu_506_p2 );
    sensitive << ( left_score_fu_483_p2 );

    SC_METHOD(thread_icmp_ln66_1_fu_576_p2);
    sensitive << ( j_2_fu_570_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( i_0_i2_reg_292 );

    SC_METHOD(thread_icmp_ln66_fu_548_p2);
    sensitive << ( j_fu_542_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( i_0_i_reg_271 );

    SC_METHOD(thread_j_1_fu_391_p2);
    sensitive << ( j_0_load_reg_627 );

    SC_METHOD(thread_j_2_fu_570_p2);
    sensitive << ( j_0_in_i3_reg_303 );

    SC_METHOD(thread_j_fu_542_p2);
    sensitive << ( j_0_in_i_reg_282 );

    SC_METHOD(thread_left_score_fu_483_p2);
    sensitive << ( H_q0 );

    SC_METHOD(thread_mul_ln130_fu_598_p0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_mul_ln130_fu_598_p1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_fu_58 );

    SC_METHOD(thread_mul_ln133_fu_605_p0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_mul_ln133_fu_605_p1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( i_fu_410_p2 );

    SC_METHOD(thread_select_ln134_fu_458_p3);
    sensitive << ( icmp_ln134_fu_452_p2 );

    SC_METHOD(thread_seq1_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( zext_ln133_1_fu_415_p1 );

    SC_METHOD(thread_seq1_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_seq2_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( zext_ln133_fu_396_p1 );

    SC_METHOD(thread_seq2_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_sext_ln130_fu_380_p1);
    sensitive << ( add_ln130_fu_375_p2 );

    SC_METHOD(thread_sext_ln133_fu_429_p1);
    sensitive << ( add_ln133_2_fu_424_p2 );

    SC_METHOD(thread_sext_ln140_fu_444_p1);
    sensitive << ( add_ln140_reg_676 );

    SC_METHOD(thread_sext_ln141_fu_448_p1);
    sensitive << ( add_ln141_reg_691 );

    SC_METHOD(thread_sext_ln145_fu_536_p1);
    sensitive << ( len_assign_reg_259 );

    SC_METHOD(thread_sext_ln150_fu_530_p1);
    sensitive << ( len_assign_reg_259 );

    SC_METHOD(thread_sext_ln155_fu_523_p1);
    sensitive << ( len_assign_reg_259 );

    SC_METHOD(thread_sext_ln165_fu_438_p1);
    sensitive << ( len_assign_reg_259 );

    SC_METHOD(thread_sext_ln68_1_fu_588_p1);
    sensitive << ( i_0_i2_reg_292 );

    SC_METHOD(thread_sext_ln68_fu_560_p1);
    sensitive << ( i_0_i_reg_271 );

    SC_METHOD(thread_sext_ln69_1_fu_593_p1);
    sensitive << ( j_2_fu_570_p2 );

    SC_METHOD(thread_sext_ln69_fu_565_p1);
    sensitive << ( j_fu_542_p2 );

    SC_METHOD(thread_trunc_ln130_fu_367_p1);
    sensitive << ( j_0_fu_54 );

    SC_METHOD(thread_trunc_ln140_fu_401_p1);
    sensitive << ( j_1_fu_391_p2 );

    SC_METHOD(thread_up_score_fu_489_p2);
    sensitive << ( H_q1 );

    SC_METHOD(thread_zext_ln133_1_fu_415_p1);
    sensitive << ( i_fu_410_p2 );

    SC_METHOD(thread_zext_ln133_fu_396_p1);
    sensitive << ( j_1_fu_391_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( and_ln127_reg_637 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln130_fu_385_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln66_fu_548_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln66_1_fu_576_p2 );

    ap_CS_fsm = "00000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "traceback_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, seq1_address0, "(port)seq1_address0");
    sc_trace(mVcdFile, seq1_ce0, "(port)seq1_ce0");
    sc_trace(mVcdFile, seq1_q0, "(port)seq1_q0");
    sc_trace(mVcdFile, seq2_address0, "(port)seq2_address0");
    sc_trace(mVcdFile, seq2_ce0, "(port)seq2_ce0");
    sc_trace(mVcdFile, seq2_q0, "(port)seq2_q0");
    sc_trace(mVcdFile, H_address0, "(port)H_address0");
    sc_trace(mVcdFile, H_ce0, "(port)H_ce0");
    sc_trace(mVcdFile, H_q0, "(port)H_q0");
    sc_trace(mVcdFile, H_address1, "(port)H_address1");
    sc_trace(mVcdFile, H_ce1, "(port)H_ce1");
    sc_trace(mVcdFile, H_q1, "(port)H_q1");
    sc_trace(mVcdFile, pos_0_read, "(port)pos_0_read");
    sc_trace(mVcdFile, pos_1_read, "(port)pos_1_read");
    sc_trace(mVcdFile, aligned_seq1_address0, "(port)aligned_seq1_address0");
    sc_trace(mVcdFile, aligned_seq1_ce0, "(port)aligned_seq1_ce0");
    sc_trace(mVcdFile, aligned_seq1_we0, "(port)aligned_seq1_we0");
    sc_trace(mVcdFile, aligned_seq1_d0, "(port)aligned_seq1_d0");
    sc_trace(mVcdFile, aligned_seq1_q0, "(port)aligned_seq1_q0");
    sc_trace(mVcdFile, aligned_seq2_address0, "(port)aligned_seq2_address0");
    sc_trace(mVcdFile, aligned_seq2_ce0, "(port)aligned_seq2_ce0");
    sc_trace(mVcdFile, aligned_seq2_we0, "(port)aligned_seq2_we0");
    sc_trace(mVcdFile, aligned_seq2_d0, "(port)aligned_seq2_d0");
    sc_trace(mVcdFile, aligned_seq2_q0, "(port)aligned_seq2_q0");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, j_0_load_reg_627, "j_0_load_reg_627");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i_0_load_reg_632, "i_0_load_reg_632");
    sc_trace(mVcdFile, and_ln127_fu_355_p2, "and_ln127_fu_355_p2");
    sc_trace(mVcdFile, and_ln127_reg_637, "and_ln127_reg_637");
    sc_trace(mVcdFile, add_ln146_fu_361_p2, "add_ln146_fu_361_p2");
    sc_trace(mVcdFile, add_ln146_reg_641, "add_ln146_reg_641");
    sc_trace(mVcdFile, trunc_ln130_fu_367_p1, "trunc_ln130_fu_367_p1");
    sc_trace(mVcdFile, trunc_ln130_reg_646, "trunc_ln130_reg_646");
    sc_trace(mVcdFile, mul_ln130_fu_598_p2, "mul_ln130_fu_598_p2");
    sc_trace(mVcdFile, mul_ln130_reg_651, "mul_ln130_reg_651");
    sc_trace(mVcdFile, H_load_reg_661, "H_load_reg_661");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, j_1_fu_391_p2, "j_1_fu_391_p2");
    sc_trace(mVcdFile, j_1_reg_671, "j_1_reg_671");
    sc_trace(mVcdFile, icmp_ln130_fu_385_p2, "icmp_ln130_fu_385_p2");
    sc_trace(mVcdFile, add_ln140_fu_405_p2, "add_ln140_fu_405_p2");
    sc_trace(mVcdFile, add_ln140_reg_676, "add_ln140_reg_676");
    sc_trace(mVcdFile, i_fu_410_p2, "i_fu_410_p2");
    sc_trace(mVcdFile, i_reg_681, "i_reg_681");
    sc_trace(mVcdFile, add_ln141_fu_434_p2, "add_ln141_fu_434_p2");
    sc_trace(mVcdFile, add_ln141_reg_691, "add_ln141_reg_691");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, seq1_load_reg_716, "seq1_load_reg_716");
    sc_trace(mVcdFile, seq2_load_reg_721, "seq2_load_reg_721");
    sc_trace(mVcdFile, and_ln142_fu_477_p2, "and_ln142_fu_477_p2");
    sc_trace(mVcdFile, and_ln142_reg_726, "and_ln142_reg_726");
    sc_trace(mVcdFile, j_fu_542_p2, "j_fu_542_p2");
    sc_trace(mVcdFile, j_reg_736, "j_reg_736");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, i_1_fu_554_p2, "i_1_fu_554_p2");
    sc_trace(mVcdFile, i_1_reg_744, "i_1_reg_744");
    sc_trace(mVcdFile, aligned_seq1_addr_4_reg_749, "aligned_seq1_addr_4_reg_749");
    sc_trace(mVcdFile, icmp_ln66_fu_548_p2, "icmp_ln66_fu_548_p2");
    sc_trace(mVcdFile, aligned_seq1_addr_5_reg_754, "aligned_seq1_addr_5_reg_754");
    sc_trace(mVcdFile, j_2_fu_570_p2, "j_2_fu_570_p2");
    sc_trace(mVcdFile, j_2_reg_759, "j_2_reg_759");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, i_2_fu_582_p2, "i_2_fu_582_p2");
    sc_trace(mVcdFile, i_2_reg_767, "i_2_reg_767");
    sc_trace(mVcdFile, aligned_seq2_addr_5_reg_772, "aligned_seq2_addr_5_reg_772");
    sc_trace(mVcdFile, icmp_ln66_1_fu_576_p2, "icmp_ln66_1_fu_576_p2");
    sc_trace(mVcdFile, aligned_seq2_addr_6_reg_777, "aligned_seq2_addr_6_reg_777");
    sc_trace(mVcdFile, len_assign_reg_259, "len_assign_reg_259");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, i_0_i_reg_271, "i_0_i_reg_271");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, j_0_in_i_reg_282, "j_0_in_i_reg_282");
    sc_trace(mVcdFile, i_0_i2_reg_292, "i_0_i2_reg_292");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, j_0_in_i3_reg_303, "j_0_in_i3_reg_303");
    sc_trace(mVcdFile, sext_ln130_fu_380_p1, "sext_ln130_fu_380_p1");
    sc_trace(mVcdFile, sext_ln133_fu_429_p1, "sext_ln133_fu_429_p1");
    sc_trace(mVcdFile, zext_ln133_1_fu_415_p1, "zext_ln133_1_fu_415_p1");
    sc_trace(mVcdFile, zext_ln133_fu_396_p1, "zext_ln133_fu_396_p1");
    sc_trace(mVcdFile, sext_ln165_fu_438_p1, "sext_ln165_fu_438_p1");
    sc_trace(mVcdFile, sext_ln140_fu_444_p1, "sext_ln140_fu_444_p1");
    sc_trace(mVcdFile, sext_ln141_fu_448_p1, "sext_ln141_fu_448_p1");
    sc_trace(mVcdFile, sext_ln155_fu_523_p1, "sext_ln155_fu_523_p1");
    sc_trace(mVcdFile, and_ln148_fu_506_p2, "and_ln148_fu_506_p2");
    sc_trace(mVcdFile, and_ln153_fu_517_p2, "and_ln153_fu_517_p2");
    sc_trace(mVcdFile, aligned_seq2_addr_3_gep_fu_186_p3, "aligned_seq2_addr_3_gep_fu_186_p3");
    sc_trace(mVcdFile, sext_ln150_fu_530_p1, "sext_ln150_fu_530_p1");
    sc_trace(mVcdFile, sext_ln145_fu_536_p1, "sext_ln145_fu_536_p1");
    sc_trace(mVcdFile, sext_ln68_fu_560_p1, "sext_ln68_fu_560_p1");
    sc_trace(mVcdFile, sext_ln69_fu_565_p1, "sext_ln69_fu_565_p1");
    sc_trace(mVcdFile, sext_ln68_1_fu_588_p1, "sext_ln68_1_fu_588_p1");
    sc_trace(mVcdFile, sext_ln69_1_fu_593_p1, "sext_ln69_1_fu_593_p1");
    sc_trace(mVcdFile, j_0_fu_54, "j_0_fu_54");
    sc_trace(mVcdFile, i_0_fu_58, "i_0_fu_58");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, icmp_ln127_fu_343_p2, "icmp_ln127_fu_343_p2");
    sc_trace(mVcdFile, icmp_ln127_1_fu_349_p2, "icmp_ln127_1_fu_349_p2");
    sc_trace(mVcdFile, add_ln130_fu_375_p2, "add_ln130_fu_375_p2");
    sc_trace(mVcdFile, trunc_ln140_fu_401_p1, "trunc_ln140_fu_401_p1");
    sc_trace(mVcdFile, mul_ln133_fu_605_p2, "mul_ln133_fu_605_p2");
    sc_trace(mVcdFile, add_ln133_2_fu_424_p2, "add_ln133_2_fu_424_p2");
    sc_trace(mVcdFile, icmp_ln134_fu_452_p2, "icmp_ln134_fu_452_p2");
    sc_trace(mVcdFile, select_ln134_fu_458_p3, "select_ln134_fu_458_p3");
    sc_trace(mVcdFile, diag_score_1_fu_466_p2, "diag_score_1_fu_466_p2");
    sc_trace(mVcdFile, grp_fu_313_p2, "grp_fu_313_p2");
    sc_trace(mVcdFile, icmp_ln142_1_fu_472_p2, "icmp_ln142_1_fu_472_p2");
    sc_trace(mVcdFile, up_score_fu_489_p2, "up_score_fu_489_p2");
    sc_trace(mVcdFile, icmp_ln148_fu_495_p2, "icmp_ln148_fu_495_p2");
    sc_trace(mVcdFile, icmp_ln148_1_fu_501_p2, "icmp_ln148_1_fu_501_p2");
    sc_trace(mVcdFile, left_score_fu_483_p2, "left_score_fu_483_p2");
    sc_trace(mVcdFile, icmp_ln153_1_fu_512_p2, "icmp_ln153_1_fu_512_p2");
    sc_trace(mVcdFile, mul_ln130_fu_598_p0, "mul_ln130_fu_598_p0");
    sc_trace(mVcdFile, mul_ln130_fu_598_p1, "mul_ln130_fu_598_p1");
    sc_trace(mVcdFile, mul_ln133_fu_605_p0, "mul_ln133_fu_605_p0");
    sc_trace(mVcdFile, mul_ln133_fu_605_p1, "mul_ln133_fu_605_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

traceback::~traceback() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete SmithWaterman_mulbkb_U6;
    delete SmithWaterman_mulbkb_U7;
}

void traceback::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln142_reg_726.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln148_fu_506_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln153_fu_517_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln142_reg_726.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, and_ln148_fu_506_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, and_ln142_reg_726.read())))) {
        i_0_fu_58 = i_reg_681.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_fu_58 = pos_0_read.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln66_fu_548_p2.read()))) {
        i_0_i2_reg_292 = ap_const_lv32_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        i_0_i2_reg_292 = i_2_reg_767.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        i_0_i_reg_271 = i_1_reg_744.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln130_fu_385_p2.read()) || 
                 esl_seteq<1,1,1>(and_ln127_reg_637.read(), ap_const_lv1_0)))) {
        i_0_i_reg_271 = ap_const_lv32_0;
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln142_reg_726.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln148_fu_506_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln153_fu_517_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln142_reg_726.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln148_fu_506_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, and_ln153_fu_517_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, and_ln142_reg_726.read())))) {
        j_0_fu_54 = j_1_reg_671.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        j_0_fu_54 = pos_1_read.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln66_fu_548_p2.read()))) {
        j_0_in_i3_reg_303 = len_assign_reg_259.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        j_0_in_i3_reg_303 = j_2_reg_759.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        j_0_in_i_reg_282 = j_reg_736.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln130_fu_385_p2.read()) || 
                 esl_seteq<1,1,1>(and_ln127_reg_637.read(), ap_const_lv1_0)))) {
        j_0_in_i_reg_282 = len_assign_reg_259.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        len_assign_reg_259 = add_ln146_reg_641.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        len_assign_reg_259 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(and_ln127_reg_637.read(), ap_const_lv1_1))) {
        H_load_reg_661 = H_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(and_ln127_reg_637.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(icmp_ln130_fu_385_p2.read(), ap_const_lv1_0))) {
        add_ln140_reg_676 = add_ln140_fu_405_p2.read();
        add_ln141_reg_691 = add_ln141_fu_434_p2.read();
        i_reg_681 = i_fu_410_p2.read();
        j_1_reg_671 = j_1_fu_391_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        add_ln146_reg_641 = add_ln146_fu_361_p2.read();
        and_ln127_reg_637 = and_ln127_fu_355_p2.read();
        i_0_load_reg_632 = i_0_fu_58.read();
        j_0_load_reg_627 = j_0_fu_54.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln66_fu_548_p2.read()))) {
        aligned_seq1_addr_4_reg_749 =  (sc_lv<7>) (sext_ln68_fu_560_p1.read());
        aligned_seq1_addr_5_reg_754 =  (sc_lv<7>) (sext_ln69_fu_565_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln66_1_fu_576_p2.read()))) {
        aligned_seq2_addr_5_reg_772 =  (sc_lv<7>) (sext_ln68_1_fu_588_p1.read());
        aligned_seq2_addr_6_reg_777 =  (sc_lv<7>) (sext_ln69_1_fu_593_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        and_ln142_reg_726 = and_ln142_fu_477_p2.read();
        seq1_load_reg_716 = seq1_q0.read();
        seq2_load_reg_721 = seq2_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        i_1_reg_744 = i_1_fu_554_p2.read();
        j_reg_736 = j_fu_542_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        i_2_reg_767 = i_2_fu_582_p2.read();
        j_2_reg_759 = j_2_fu_570_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(and_ln127_fu_355_p2.read(), ap_const_lv1_1))) {
        mul_ln130_reg_651 = mul_ln130_fu_598_p2.read();
        trunc_ln130_reg_646 = trunc_ln130_fu_367_p1.read();
    }
}

void traceback::thread_H_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        H_address0 =  (sc_lv<14>) (sext_ln140_fu_444_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        H_address0 =  (sc_lv<14>) (sext_ln133_fu_429_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        H_address0 =  (sc_lv<14>) (sext_ln130_fu_380_p1.read());
    } else {
        H_address0 = "XXXXXXXXXXXXXX";
    }
}

void traceback::thread_H_address1() {
    H_address1 =  (sc_lv<14>) (sext_ln141_fu_448_p1.read());
}

void traceback::thread_H_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        H_ce0 = ap_const_logic_1;
    } else {
        H_ce0 = ap_const_logic_0;
    }
}

void traceback::thread_H_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        H_ce1 = ap_const_logic_1;
    } else {
        H_ce1 = ap_const_logic_0;
    }
}

void traceback::thread_add_ln130_fu_375_p2() {
    add_ln130_fu_375_p2 = (!mul_ln130_fu_598_p2.read().is_01() || !trunc_ln130_fu_367_p1.read().is_01())? sc_lv<15>(): (sc_bigint<15>(mul_ln130_fu_598_p2.read()) + sc_biguint<15>(trunc_ln130_fu_367_p1.read()));
}

void traceback::thread_add_ln133_2_fu_424_p2() {
    add_ln133_2_fu_424_p2 = (!mul_ln133_fu_605_p2.read().is_01() || !trunc_ln140_fu_401_p1.read().is_01())? sc_lv<15>(): (sc_bigint<15>(mul_ln133_fu_605_p2.read()) + sc_biguint<15>(trunc_ln140_fu_401_p1.read()));
}

void traceback::thread_add_ln140_fu_405_p2() {
    add_ln140_fu_405_p2 = (!mul_ln130_reg_651.read().is_01() || !trunc_ln140_fu_401_p1.read().is_01())? sc_lv<15>(): (sc_bigint<15>(mul_ln130_reg_651.read()) + sc_biguint<15>(trunc_ln140_fu_401_p1.read()));
}

void traceback::thread_add_ln141_fu_434_p2() {
    add_ln141_fu_434_p2 = (!mul_ln133_fu_605_p2.read().is_01() || !trunc_ln130_reg_646.read().is_01())? sc_lv<15>(): (sc_bigint<15>(mul_ln133_fu_605_p2.read()) + sc_biguint<15>(trunc_ln130_reg_646.read()));
}

void traceback::thread_add_ln146_fu_361_p2() {
    add_ln146_fu_361_p2 = (!len_assign_reg_259.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(len_assign_reg_259.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void traceback::thread_aligned_seq1_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        aligned_seq1_address0 = aligned_seq1_addr_5_reg_754.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        aligned_seq1_address0 = aligned_seq1_addr_4_reg_749.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        aligned_seq1_address0 =  (sc_lv<7>) (sext_ln69_fu_565_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, and_ln142_reg_726.read()))) {
        aligned_seq1_address0 =  (sc_lv<7>) (sext_ln145_fu_536_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, and_ln142_reg_726.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, and_ln148_fu_506_p2.read()))) {
        aligned_seq1_address0 =  (sc_lv<7>) (sext_ln150_fu_530_p1.read());
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, and_ln142_reg_726.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, and_ln148_fu_506_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, and_ln153_fu_517_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, and_ln142_reg_726.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, and_ln148_fu_506_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, and_ln153_fu_517_p2.read())))) {
        aligned_seq1_address0 =  (sc_lv<7>) (sext_ln155_fu_523_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        aligned_seq1_address0 =  (sc_lv<7>) (sext_ln165_fu_438_p1.read());
    } else {
        aligned_seq1_address0 =  (sc_lv<7>) ("XXXXXXX");
    }
}

void traceback::thread_aligned_seq1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln142_reg_726.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln148_fu_506_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln153_fu_517_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln142_reg_726.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln148_fu_506_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, and_ln153_fu_517_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln142_reg_726.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, and_ln148_fu_506_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, and_ln142_reg_726.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        aligned_seq1_ce0 = ap_const_logic_1;
    } else {
        aligned_seq1_ce0 = ap_const_logic_0;
    }
}

void traceback::thread_aligned_seq1_d0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        aligned_seq1_d0 = aligned_seq1_q0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, and_ln142_reg_726.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, and_ln148_fu_506_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, and_ln153_fu_517_p2.read()))) {
        aligned_seq1_d0 = ap_const_lv8_2D;
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, and_ln142_reg_726.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, and_ln148_fu_506_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, and_ln153_fu_517_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, and_ln142_reg_726.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, and_ln148_fu_506_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, and_ln142_reg_726.read())))) {
        aligned_seq1_d0 = seq1_load_reg_716.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        aligned_seq1_d0 = ap_const_lv8_0;
    } else {
        aligned_seq1_d0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void traceback::thread_aligned_seq1_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln130_fu_385_p2.read()) || 
           esl_seteq<1,1,1>(and_ln127_reg_637.read(), ap_const_lv1_0))) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln142_reg_726.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln148_fu_506_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln153_fu_517_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln142_reg_726.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln148_fu_506_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, and_ln153_fu_517_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln142_reg_726.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, and_ln148_fu_506_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, and_ln142_reg_726.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        aligned_seq1_we0 = ap_const_logic_1;
    } else {
        aligned_seq1_we0 = ap_const_logic_0;
    }
}

void traceback::thread_aligned_seq2_addr_3_gep_fu_186_p3() {
    aligned_seq2_addr_3_gep_fu_186_p3 =  (sc_lv<7>) (sext_ln155_fu_523_p1.read());
}

void traceback::thread_aligned_seq2_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        aligned_seq2_address0 = aligned_seq2_addr_6_reg_777.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        aligned_seq2_address0 = aligned_seq2_addr_5_reg_772.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        aligned_seq2_address0 =  (sc_lv<7>) (sext_ln69_1_fu_593_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, and_ln142_reg_726.read()))) {
        aligned_seq2_address0 =  (sc_lv<7>) (sext_ln145_fu_536_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, and_ln142_reg_726.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, and_ln148_fu_506_p2.read()))) {
        aligned_seq2_address0 =  (sc_lv<7>) (sext_ln150_fu_530_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, and_ln142_reg_726.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, and_ln148_fu_506_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, and_ln153_fu_517_p2.read()))) {
        aligned_seq2_address0 = aligned_seq2_addr_3_gep_fu_186_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, and_ln142_reg_726.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, and_ln148_fu_506_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, and_ln153_fu_517_p2.read()))) {
        aligned_seq2_address0 =  (sc_lv<7>) (sext_ln155_fu_523_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        aligned_seq2_address0 =  (sc_lv<7>) (sext_ln165_fu_438_p1.read());
    } else {
        aligned_seq2_address0 =  (sc_lv<7>) ("XXXXXXX");
    }
}

void traceback::thread_aligned_seq2_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln142_reg_726.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln148_fu_506_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln153_fu_517_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln142_reg_726.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln148_fu_506_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, and_ln153_fu_517_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln142_reg_726.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, and_ln148_fu_506_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, and_ln142_reg_726.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        aligned_seq2_ce0 = ap_const_logic_1;
    } else {
        aligned_seq2_ce0 = ap_const_logic_0;
    }
}

void traceback::thread_aligned_seq2_d0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        aligned_seq2_d0 = aligned_seq2_q0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, and_ln142_reg_726.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, and_ln148_fu_506_p2.read()))) {
        aligned_seq2_d0 = ap_const_lv8_2D;
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, and_ln142_reg_726.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, and_ln148_fu_506_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, and_ln153_fu_517_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, and_ln142_reg_726.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, and_ln148_fu_506_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, and_ln153_fu_517_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, and_ln142_reg_726.read())))) {
        aligned_seq2_d0 = seq2_load_reg_721.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        aligned_seq2_d0 = ap_const_lv8_0;
    } else {
        aligned_seq2_d0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void traceback::thread_aligned_seq2_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln130_fu_385_p2.read()) || 
           esl_seteq<1,1,1>(and_ln127_reg_637.read(), ap_const_lv1_0))) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln142_reg_726.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln148_fu_506_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln153_fu_517_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln142_reg_726.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln148_fu_506_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, and_ln153_fu_517_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, and_ln142_reg_726.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, and_ln148_fu_506_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, and_ln142_reg_726.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        aligned_seq2_we0 = ap_const_logic_1;
    } else {
        aligned_seq2_we0 = ap_const_logic_0;
    }
}

void traceback::thread_and_ln127_fu_355_p2() {
    and_ln127_fu_355_p2 = (icmp_ln127_fu_343_p2.read() & icmp_ln127_1_fu_349_p2.read());
}

void traceback::thread_and_ln142_fu_477_p2() {
    and_ln142_fu_477_p2 = (grp_fu_313_p2.read() & icmp_ln142_1_fu_472_p2.read());
}

void traceback::thread_and_ln148_fu_506_p2() {
    and_ln148_fu_506_p2 = (icmp_ln148_fu_495_p2.read() & icmp_ln148_1_fu_501_p2.read());
}

void traceback::thread_and_ln153_fu_517_p2() {
    and_ln153_fu_517_p2 = (grp_fu_313_p2.read() & icmp_ln153_1_fu_512_p2.read());
}

void traceback::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void traceback::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void traceback::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void traceback::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void traceback::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void traceback::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void traceback::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void traceback::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void traceback::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void traceback::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void traceback::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void traceback::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln66_1_fu_576_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void traceback::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void traceback::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln66_1_fu_576_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void traceback::thread_ap_return() {
    ap_return = len_assign_reg_259.read();
}

void traceback::thread_diag_score_1_fu_466_p2() {
    diag_score_1_fu_466_p2 = (!select_ln134_fu_458_p3.read().is_01() || !H_q0.read().is_01())? sc_lv<32>(): (sc_biguint<32>(select_ln134_fu_458_p3.read()) + sc_biguint<32>(H_q0.read()));
}

void traceback::thread_grp_fu_313_p2() {
    grp_fu_313_p2 = (!H_q0.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(H_q0.read() != ap_const_lv32_0);
}

void traceback::thread_i_1_fu_554_p2() {
    i_1_fu_554_p2 = (!i_0_i_reg_271.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(i_0_i_reg_271.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void traceback::thread_i_2_fu_582_p2() {
    i_2_fu_582_p2 = (!i_0_i2_reg_292.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(i_0_i2_reg_292.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void traceback::thread_i_fu_410_p2() {
    i_fu_410_p2 = (!ap_const_lv32_FFFFFFFF.is_01() || !i_0_load_reg_632.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFFF) + sc_biguint<32>(i_0_load_reg_632.read()));
}

void traceback::thread_icmp_ln127_1_fu_349_p2() {
    icmp_ln127_1_fu_349_p2 = (!j_0_fu_54.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(j_0_fu_54.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void traceback::thread_icmp_ln127_fu_343_p2() {
    icmp_ln127_fu_343_p2 = (!i_0_fu_58.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(i_0_fu_58.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void traceback::thread_icmp_ln130_fu_385_p2() {
    icmp_ln130_fu_385_p2 = (!H_q0.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(H_q0.read() == ap_const_lv32_0);
}

void traceback::thread_icmp_ln134_fu_452_p2() {
    icmp_ln134_fu_452_p2 = (!seq1_q0.read().is_01() || !seq2_q0.read().is_01())? sc_lv<1>(): sc_lv<1>(seq1_q0.read() == seq2_q0.read());
}

void traceback::thread_icmp_ln142_1_fu_472_p2() {
    icmp_ln142_1_fu_472_p2 = (!diag_score_1_fu_466_p2.read().is_01() || !H_load_reg_661.read().is_01())? sc_lv<1>(): sc_lv<1>(diag_score_1_fu_466_p2.read() == H_load_reg_661.read());
}

void traceback::thread_icmp_ln148_1_fu_501_p2() {
    icmp_ln148_1_fu_501_p2 = (!up_score_fu_489_p2.read().is_01() || !H_load_reg_661.read().is_01())? sc_lv<1>(): sc_lv<1>(up_score_fu_489_p2.read() == H_load_reg_661.read());
}

void traceback::thread_icmp_ln148_fu_495_p2() {
    icmp_ln148_fu_495_p2 = (!H_q1.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(H_q1.read() != ap_const_lv32_0);
}

void traceback::thread_icmp_ln153_1_fu_512_p2() {
    icmp_ln153_1_fu_512_p2 = (!left_score_fu_483_p2.read().is_01() || !H_load_reg_661.read().is_01())? sc_lv<1>(): sc_lv<1>(left_score_fu_483_p2.read() == H_load_reg_661.read());
}

void traceback::thread_icmp_ln66_1_fu_576_p2() {
    icmp_ln66_1_fu_576_p2 = (!i_0_i2_reg_292.read().is_01() || !j_2_fu_570_p2.read().is_01())? sc_lv<1>(): (sc_bigint<32>(i_0_i2_reg_292.read()) < sc_bigint<32>(j_2_fu_570_p2.read()));
}

void traceback::thread_icmp_ln66_fu_548_p2() {
    icmp_ln66_fu_548_p2 = (!i_0_i_reg_271.read().is_01() || !j_fu_542_p2.read().is_01())? sc_lv<1>(): (sc_bigint<32>(i_0_i_reg_271.read()) < sc_bigint<32>(j_fu_542_p2.read()));
}

void traceback::thread_j_1_fu_391_p2() {
    j_1_fu_391_p2 = (!ap_const_lv32_FFFFFFFF.is_01() || !j_0_load_reg_627.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFFF) + sc_biguint<32>(j_0_load_reg_627.read()));
}

void traceback::thread_j_2_fu_570_p2() {
    j_2_fu_570_p2 = (!j_0_in_i3_reg_303.read().is_01() || !ap_const_lv32_FFFFFFFF.is_01())? sc_lv<32>(): (sc_biguint<32>(j_0_in_i3_reg_303.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFFF));
}

void traceback::thread_j_fu_542_p2() {
    j_fu_542_p2 = (!j_0_in_i_reg_282.read().is_01() || !ap_const_lv32_FFFFFFFF.is_01())? sc_lv<32>(): (sc_biguint<32>(j_0_in_i_reg_282.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFFF));
}

void traceback::thread_left_score_fu_483_p2() {
    left_score_fu_483_p2 = (!ap_const_lv32_FFFFFFFE.is_01() || !H_q0.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFFE) + sc_biguint<32>(H_q0.read()));
}

void traceback::thread_mul_ln130_fu_598_p0() {
    mul_ln130_fu_598_p0 =  (sc_lv<8>) (ap_const_lv15_65);
}

void traceback::thread_mul_ln130_fu_598_p1() {
    mul_ln130_fu_598_p1 = i_0_fu_58.read().range(15-1, 0);
}

void traceback::thread_mul_ln133_fu_605_p0() {
    mul_ln133_fu_605_p0 =  (sc_lv<8>) (ap_const_lv15_65);
}

void traceback::thread_mul_ln133_fu_605_p1() {
    mul_ln133_fu_605_p1 = i_fu_410_p2.read().range(15-1, 0);
}

void traceback::thread_select_ln134_fu_458_p3() {
    select_ln134_fu_458_p3 = (!icmp_ln134_fu_452_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln134_fu_452_p2.read()[0].to_bool())? ap_const_lv32_3: ap_const_lv32_FFFFFFFD);
}

void traceback::thread_seq1_address0() {
    seq1_address0 =  (sc_lv<7>) (zext_ln133_1_fu_415_p1.read());
}

void traceback::thread_seq1_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        seq1_ce0 = ap_const_logic_1;
    } else {
        seq1_ce0 = ap_const_logic_0;
    }
}

void traceback::thread_seq2_address0() {
    seq2_address0 =  (sc_lv<7>) (zext_ln133_fu_396_p1.read());
}

void traceback::thread_seq2_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        seq2_ce0 = ap_const_logic_1;
    } else {
        seq2_ce0 = ap_const_logic_0;
    }
}

void traceback::thread_sext_ln130_fu_380_p1() {
    sext_ln130_fu_380_p1 = esl_sext<64,15>(add_ln130_fu_375_p2.read());
}

void traceback::thread_sext_ln133_fu_429_p1() {
    sext_ln133_fu_429_p1 = esl_sext<64,15>(add_ln133_2_fu_424_p2.read());
}

void traceback::thread_sext_ln140_fu_444_p1() {
    sext_ln140_fu_444_p1 = esl_sext<64,15>(add_ln140_reg_676.read());
}

void traceback::thread_sext_ln141_fu_448_p1() {
    sext_ln141_fu_448_p1 = esl_sext<64,15>(add_ln141_reg_691.read());
}

void traceback::thread_sext_ln145_fu_536_p1() {
    sext_ln145_fu_536_p1 = esl_sext<64,32>(len_assign_reg_259.read());
}

void traceback::thread_sext_ln150_fu_530_p1() {
    sext_ln150_fu_530_p1 = esl_sext<64,32>(len_assign_reg_259.read());
}

void traceback::thread_sext_ln155_fu_523_p1() {
    sext_ln155_fu_523_p1 = esl_sext<64,32>(len_assign_reg_259.read());
}

void traceback::thread_sext_ln165_fu_438_p1() {
    sext_ln165_fu_438_p1 = esl_sext<64,32>(len_assign_reg_259.read());
}

void traceback::thread_sext_ln68_1_fu_588_p1() {
    sext_ln68_1_fu_588_p1 = esl_sext<64,32>(i_0_i2_reg_292.read());
}

void traceback::thread_sext_ln68_fu_560_p1() {
    sext_ln68_fu_560_p1 = esl_sext<64,32>(i_0_i_reg_271.read());
}

void traceback::thread_sext_ln69_1_fu_593_p1() {
    sext_ln69_1_fu_593_p1 = esl_sext<64,32>(j_2_fu_570_p2.read());
}

void traceback::thread_sext_ln69_fu_565_p1() {
    sext_ln69_fu_565_p1 = esl_sext<64,32>(j_fu_542_p2.read());
}

void traceback::thread_trunc_ln130_fu_367_p1() {
    trunc_ln130_fu_367_p1 = j_0_fu_54.read().range(15-1, 0);
}

void traceback::thread_trunc_ln140_fu_401_p1() {
    trunc_ln140_fu_401_p1 = j_1_fu_391_p2.read().range(15-1, 0);
}

void traceback::thread_up_score_fu_489_p2() {
    up_score_fu_489_p2 = (!ap_const_lv32_FFFFFFFE.is_01() || !H_q1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFFE) + sc_biguint<32>(H_q1.read()));
}

void traceback::thread_zext_ln133_1_fu_415_p1() {
    zext_ln133_1_fu_415_p1 = esl_zext<64,32>(i_fu_410_p2.read());
}

void traceback::thread_zext_ln133_fu_396_p1() {
    zext_ln133_fu_396_p1 = esl_zext<64,32>(j_1_fu_391_p2.read());
}

void traceback::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln130_fu_385_p2.read()) || 
  esl_seteq<1,1,1>(and_ln127_reg_637.read(), ap_const_lv1_0)))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln66_fu_548_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln66_1_fu_576_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<11>) ("XXXXXXXXXXX");
            break;
    }
}

}

